version: '3.7'

services:
        elasticsearch:
          image: elasticsearch:8.4.3
          ports:
            - '9206:9200'
        environment:
            - discovery.type=single-node
        ulimits:
         memlock:
            soft: -1
            hard: -1
        kibana:
          image: kibana:8.4.3
          ports:
            - '5601:5601'